---
  - hosts: sitop-centos-backend02
    gather_facts: yes
    become: true
    tasks:
    - name: set hostname "{{ inventory_hostname }}"
      shell: |
        hostnamectl set-hostname "sitop-centos-backend02" --static
        hostnamectl set-hostname "Backend - Tomcat - Server" --pretty
        cp -p /etc/hosts /etc/hosts.ORI
        echo "10.10.129.143   sitop-centos-backend02" >> /etc/hosts

    - name: restart system
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0

    - name: wait for the system to reboot
      wait_for_connection:
          connect_timeout: 20
          sleep: 5
          delay: 5
          timeout: 60

    - name: check hostname in "{{ inventory_hostname }}"
      shell: |
        hostnamectl
